### ISSUE TITLE
Fraction for 1/3 measurements

### ISSUE THREAD

**Issue by taylorcollins** [nystudio107/recipe#3]
Can you add cases that allow for .333 and .666 to show 1/3 and 1/6 fractions when output? Right now to do 1/3 measurements you have to leave the quantity blank and write "1/3" in the ingredient field which outputs differently than the superscript/subscript fraction. It's confusing for our admin users to have .333 output 33300/100000.

Thanks for your consideration!

**Comment by khalwat** [comment]
Check out the build in the `develop` branch:

https://github.com/nystudio107/recipe/tree/develop

**Comment by taylorcollins** [comment]
love it!
