### ISSUE TITLE
New Feature Request: Image for each step of the directions

### ISSUE THREAD

**Issue by richhayler** [nystudio107/recipe#4]
Awesome work producing such a wonderful plugin - thank you.

Only request is to have an optional image asset to attach to each step of the directions as a visual reference to the novice chef! :)

**Comment by khalwat** [comment]
What you could do is have an Assets field in your layout where you could add images that correspond to each step.

I'm leery about putting _too_ much into the core plugin itself

**Comment by richhayler** [comment]
That's fair. And a reasonable alternative approach - thanks
